"""
:platform: Unix, Windows
:synopsis: This module is mostly generated code from QtDesigner. It describes the format of the settings
    dialog for editing the number of samples used in the window filter.
:moduleauthor: Michael Eller <mbe9a@virginia.edu>
"""

from PyQt5 import QtCore, QtGui, QtWidgets
from settings_interface import set_window_samples, get_window_samples


class Ui_Dialog(object):
    """
    The graphical structure of this *Ui_Dialog* was generated by QtDesigner.
    The window allows the user to set the number of samples used in the moving average filter.
    """

    def setupUi(self, Dialog):
        """
        This function initializes the window by altering the *Dialog* object passed (by reference) to it.

        :param Dialog: This must be of type PyQt5.QtWidgets.QDialog.
        """

        # set window name, icon, size
        Dialog.setObjectName("Settings - Window Filter")
        Dialog.setWindowIcon(QtGui.QIcon('resources/gear.ico'))
        Dialog.resize(400, 300)

        # make a grid layout
        # grid layouts allow the window to be resized easily
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")

        # the following spacer items organize the objects in the window nicely
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)

        # create a save and cancel button, these are built in buttons that emit specific signals
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 3, 1, 1)

        # create the input box for the number of samples
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(8)
        self.spinBox.setObjectName("spinBox")
        num = int(get_window_samples())
        self.spinBox.setValue(num)
        self.gridLayout.addWidget(self.spinBox, 2, 3, 1, 1)

        # create a label for the input box
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)

        # move the objects over to Dialog and set the text
        self.retranslateUi(Dialog)

        # set what to do when the save button is clicked
        self.buttonBox.accepted.connect(lambda: self.save(Dialog))

        # set what to do when the cancel button is hit
        self.buttonBox.rejected.connect(Dialog.reject)

        # connect the signals and slots by name
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        """
        This function translates the GUI objects of this class to the passed *Dialog* objcect,
        then sets the text of the various objects in the window.

        :param Dialog: This must be of type PyQt5.QtWidgets.QDialog.
        """

        # rename the function for readability
        _translate = QtCore.QCoreApplication.translate

        # set the window title and label text
        Dialog.setWindowTitle(_translate("Dialog", "Settings - Window Filter"))
        self.label.setText(_translate("Dialog", "Number of Samples"))

    def save(self, Dialog):
        """
        This function saves the input and closes the window.

        :param Dialog: This must be of type PyQt5.QtWidgets.QDialog.
        """

        # grab the number from the input box
        num = self.spinBox.value()

        # save it
        set_window_samples(num)

        # close the window
        Dialog.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
